name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Start DynamoDB local
        run: docker run -d -p 8000:8000 amazon/dynamodb-local

      - name: Wait for DynamoDB local
        run: |
          until nc -z localhost 8000; do sleep 1; done

      - name: Run DynamoDB script
        run: |
          node ./scripts/terminal/dynamodb.js

      - name: Add Sample Users + Product
        run: node ./scripts/terminal/insert-sample-data.js

      - name: Run tests
        run: npm test

      - name: Stop DynamoDB Local
        run: docker stop dynamodb-local
